codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch:
      default:
        target: 90
    project:
      default:
        threshold: 1%
    changes: false
comment: false
ignore:
  - "tests/"