language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: trusty
os: linux

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 examples
  - ./vendor/bin/phpcs --standard=PSR2 tests
  - php -n -dzend_extension=xdebug -dxdebug.mode=coverage ./vendor/bin/phpunit --coverage-text
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml


env:
  global:
    - XMLY_APP_KEY=99b37417e1185eda1378600593b45c40
    - XMLY_APP_SECRET=dd7a46b12fe8a304ef17892c89ede22a
    - XMLY_DEVICE_ID=32cc6f279c7a11e9a26e0235d2b38928

after_success:
  - bash <(curl -s https://codecov.io/bash)
