language: php

php:
  - 7.2
  - 7.3
  - 7.4

dist: trusty
os: linux

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update --2
  - travis_retry composer install --no-interaction  --prefer-source

script:
  - rm -rf .xmly_sdk/logs
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 examples
  - ./vendor/bin/phpcs --standard=PSR2 tests
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

env:
  global:
    - XMLY_APP_KEY=99b37417e1185eda1378600593b45c40
    - XMLY_APP_SECRET=dd7a46b12fe8a304ef17892c89ede22a
    - XMLY_DEVICE_ID=32cc6f279c7a11e9a26e0235d2b38928
    - XDEBUG_MODE=coverage